help:
	@grep '####' Makefile| grep -v grep | sed -e "s/####//"

cart: ####\t Setup Cart Component
	@bash components/cart.sh

catalogue: #### Setup catalogue component
	@bash components/catalogue.sh

user: ####\t Setup user component
	@bash components/user.sh

shipping: #### Setup shipping component
	@bash components/shipping.sh

payment: #### Setup payment component
	@bash components/payment.sh

frontend: #### Setup frontend component
	@bash components/frontend.sh

mysql: ####\t Setup MySQL component
	@bash components/mysql.sh

redis: ####\t Setup Redis component
	@bash components/redis.sh

rabbbitmq: #### Setup Rabbitmq component
	@bash components/rabbitmq.sh

mongodb: #### Setup Mongodb component
	@bash components/mongodb.sh




## targets
## 		rules

